apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: demo
immutable: false
data:
  username: admin
  password: password
  mongo.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: rs0