apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-p
  namespace: demo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-p
  template:
    metadata:
      labels:
        app: mongo-p
    spec:
      containers:
        - image: mongo
          name: mongo-p
          args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc