apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: demo
spec:
  ports:
    - port: 27107
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: mongo-p
  type: NodePort